version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "UKHomeOffice/hocs-core"
    ignore:
      - dependency-name: "com.amazonaws:aws-java-sdk-sns"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "com.amazonaws:aws-java-sdk-sqs"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "com.amazonaws:aws-java-sdk-s3"
        update-types: [ "version-update:semver-patch" ]
    labels:
      - "patch"
      - "dependencies"
