apiVersion: v1
kind: Service
metadata:
  labels:
    name: hocs-cms-data-migrator
  name: hocs-cms-data-migrator
spec:
  ports:
  - name: https
    port: 443
    targetPort: 10440
  selector:
    name: hocs-cms-data-migrator