---
kind: pipeline
type: kubernetes
name: deploy
trigger:
  event:
    - promote

steps:
  - name: fetch and checkout
    image: alpine/git
    commands:
      - git fetch --tags
      - git checkout $${VERSION}

  - name: deploy to cs-dev-migration
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-dev-migration
      KUBE_TOKEN:
        from_secret: hocs_cms_data_migrator_cs_dev_migration
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    when:
      target:
        - release
    depends_on:
      - fetch and checkout
---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  branch:
    - main
  event:
    - tag

steps:
  - name: cs-dev-migration
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-dev-migration
      KUBE_TOKEN:
        from_secret: hocs_cms_data_migrator_cs_dev_migration
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      VERSION: "${DRONE_TAG}"
    depends_on:
      - clone
...
