---
kind: pipeline
type: kubernetes
name: build
trigger:
  event:
    - push
  branch:
    exclude:
      - main

services:
  - name: sqlserver
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: Development01
      ACCEPT_EULA: Y

  - name: localstack
    image: localstack/localstack:0.14.3
    environment:
      SERVICES: sqs
      DEFAULT_REGION: eu-west-2

steps:
  - name: setup localstack
    image: localstack/localstack:0.14.3
    commands:
      - cd config/localstack
      - ./1-setup-sqs.sh
    depends_on:
      - clone

  - name: test project
    image: quay.io/ukhomeofficedigital/hocs-base-image-build:1.0.5
    environment:
      SPRING_PROFILES_ACTIVE: "localstack"
      DB_HOST: "sqlserver"
      LOCALSTACK_CONFIG_HOST: "localstack"
    commands:
      - ./gradlew clean build --no-daemon
    depends_on:
      - setup localstack

  - name: sonar scanner
    image: quay.io/ukhomeofficedigital/sonar-scanner
    commands:
      - sonar-scanner -Dsonar.projectVersion="$(git rev-parse --abbrev-ref HEAD)"
    depends_on:
      - test project

  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-cms-data-migrator
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - test project

---
kind: pipeline
type: kubernetes
name: deploy
trigger:
  event:
    - promote

steps:
  - name: fetch and checkout
    image: alpine/git
    commands:
      - git fetch --tags
      - git checkout $${VERSION}

  - name: deploy to cs-dev-migration
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-dev-migration
      KUBE_TOKEN:
        from_secret: hocs_cms_data_migrator_cs_dev_migration
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    when:
      target:
        - release
    depends_on:
      - fetch and checkout

---
kind: pipeline
type: kubernetes
name: build tag
trigger:
  event:
    - tag
  branch:
    - main

services:
  - name: sqlserver
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: Development01
      ACCEPT_EULA: Y
  - name: localstack
    image: localstack/localstack:0.14.3
    environment:
      SERVICES: sqs
      DEFAULT_REGION: eu-west-2

steps:
  - name: setup localstack
    image: localstack/localstack:0.14.3
    commands:
      - cd config/localstack
      - ./1-setup-sqs.sh
    depends_on:
      - clone

  - name: test project
    image: quay.io/ukhomeofficedigital/hocs-base-image-build:1.0.5
    environment:
      SPRING_PROFILES_ACTIVE: "localstack"
      DB_HOST: "sqlserver"
      LOCALSTACK_CONFIG_HOST: "localstack"
    commands:
      - ./gradlew clean build --no-daemon
    depends_on:
      - setup localstack

  - name: build & push tag main
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-cms-data-migrator
      tags:
        - ${DRONE_TAG}
        - ${DRONE_COMMIT_SHA}
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - test project
    when:
      branch:
        - main

---
kind: pipeline
type: kubernetes
name: deploy tag
depends_on:
  - build tag
trigger:
  branch:
    - main
  event:
    - tag

steps:
  - name: cs-dev-migration
    image: quay.io/ukhomeofficedigital/kd
    environment:
      VERSION: ${DRONE_COMMIT_SHA}
      ENVIRONMENT: cs-dev-migration
      KUBE_TOKEN:
        from_secret: hocs_cms_data_migrator_cs_dev_migration
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    commands:
      - cd kube
      - ./deploy.sh
    depends_on:
      - clone
...
