---
kind: pipeline
type: kubernetes
name: build
trigger:
  event:
    - push
  branch:
    exclude:
      - main

steps:
  - name: test project
    image: quay.io/ukhomeofficedigital/hocs-base-image-build
    environment:
      SPRING_PROFILES_ACTIVE: "local"
      LOCALSTACK_CONFIG_HOST: "localstack"
    commands:
      - ./gradlew clean build --no-daemon
    depends_on:
      - clone

  - name: sonar scanner
    image: quay.io/ukhomeofficedigital/sonar-scanner
    commands:
      - sonar-scanner -Dsonar.projectVersion="$(git rev-parse --abbrev-ref HEAD)"
    depends_on:
      - test project

  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-cms-data-migrator
      tags:
        - ${DRONE_COMMIT_SHA}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - test project

---
kind: pipeline
type: kubernetes
name: build tag
trigger:
  event:
    - tag
  branch:
    - main

services:
  - name: localstack
    image: quay.io/ukhomeofficedigital/localstack
    environment:
      SERVICES: sqs, sns
      DEFAULT_REGION: eu-west-2

steps:
  - name: setup localstack
    image: quay.io/ukhomeofficedigital/localstack
    commands:
      - cd config/localstack
      - ./1-setup-sqs.sh
      - ./2-setup-sns.sh
    depends_on:
      - clone

  - name: test project
    image: quay.io/ukhomeofficedigital/hocs-base-image-build
    environment:
      SPRING_PROFILES_ACTIVE: "local"
      LOCALSTACK_CONFIG_HOST: "localstack"
    commands:
      - ./gradlew clean build --no-daemon
    depends_on:
      - clone

  - name: sonar scanner
    image: quay.io/ukhomeofficedigital/sonar-scanner
    commands:
      - sonar-scanner -Dsonar.projectVersion="$(git rev-parse --abbrev-ref HEAD)"
    depends_on:
      - test project

  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-cms-data-migrator
      tags:
        - ${DRONE_TAG}
        - ${DRONE_COMMIT_SHA}
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - test project

---
kind: pipeline
type: kubernetes
name: build

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push

steps:
  - name: build & push
    image: plugins/docker
    depends_on:
      - clone
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-cms-data-migrator
      tags:
        - ${DRONE_COMMIT_SHA}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot

---
kind: pipeline
type: kubernetes
name: deploy tag
depends_on:
  - build

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: cs-dev-migration
    image: quay.io/ukhomeofficedigital/kd
    environment:
      VERSION: ${DRONE_COMMIT_SHA}
      KUBE_TOKEN:
        from_secret: hocs_cms_data_migrator_cs_dev_migration
    commands:
      - cd kube
      - ./deploy.sh
    depends_on:
      - clone
...


